
on:
  push:
    branches:
      - main
  workflow_dispatch:


jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: demo
        env:
           AEMBIT_CLIENT_ID: ${{ secrets.AEMBIT_CLIENT_ID }}
        run: |
           pwd
           ls
           $(./aembit credentials get --client_id $AEMBIT_CLIENT_ID --server_workload_host www.google.com --server_workload_port 443)
              echo Get OAuth Token: $TOKEN
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3.19
        timeout-minutes: 60
        with:
          limit-access-to-actor: false